spring:
  application:
    name: ecommerce-graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: create
#    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true

server:
  port: 8080
